include:
  - "apidocs/**/*"
exclude:
  - "adapters/**"
  - "authz/**"
  - "boms/**"
  - "common/**"
  - "core/**"
  - "dependencies/**"
  - "distribution/**"
  - "examples/**"
  - "federation/**"
  - "integration/**"
  - "misc/**"
  - "model/**"
  - "proxy/**"
  - "saml-core/**"
  - "saml-core-api/**"
  - "server-spi/**"
  - "server-spi-private/**"
  - "services/**"
  - "testsuite/**"
  - "themes/**"
  - "util/**"
  - "wildfly/**"
